### ISSUE TITLE
Fix errors in vignettes

### ISSUE THREAD

**Issue by Alanwe** [Microsoft/AzureSMR#75]
Authentication vignette:
* Change in portal names. 
* Users -> Access Control (IAM) (15/17)

Walkthrough
* Some UpperCamelCase functions
* Some Az naming issues

Blob Storage Authentication - Could be clearer, Authentication without AD example

**Comment by andrie** [comment]
Thanks for flagging an assigning yourself.

While you're at it, can you please try to write the examples in such a way the functions will run without errors in Azure?

For example, illustrate the end-to-end flow of creating a resource, doing something with it, and then deleting the resource.

In this way, we can run the tests automatically to detect errors as part of package building.

As the examples are written now, mostly all of them will fail with errors, since the resources don't actually exist.

**Comment by Alanwe** [comment]
Sure, already starting to do so. It used to work like that however it needs updating to reflect some of the changes.

**Comment by andrie** [comment]
Hmm.  As the tutorial stands, for most of the examples you needed to have an existing Azure resource with the name you gave it. If any other user doesn't have an existing resource with that name, then the example will fail.
